import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/commoncomponent/navbar/navbar'
import Footer from './components/commoncomponent/footer/footer'
import Work from './components/homepage/workwithme/work'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      {children}
      <Work/>
      <Footer/>
      </body>
    </html>
  )
}
